@hostname = localhost
@port = 7111
@host = https://{{hostname}}:{{port}}
@contentType = application/json


### AddDog #############################################################################################################

### Regular use (WaltDisney Pluto) -------------------------------------------------------------------------------------
POST {{host}}/api/Dog/AddDog
Content-Type:{{contentType}}

{
	"name": "Pluto",
	"breedId": 45
}

### Regular use (Marley and me) -----------------------------------------------------------------------------------------
POST {{host}}/api/Dog/AddDog
Content-Type:{{contentType}}

{
	"name": "Marley",
	"breedId": 149
}

### Regular use (Beethoven movie) --------------------------------------------------------------------------------------
POST {{host}}/api/Dog/AddDog
Content-Type:{{contentType}}

{
	"name": "Beethoven",
	"breedId": 212
}

### Regular use (The Mask's dog) --------------------------------------------------------------------------------------
POST {{host}}/api/Dog/AddDog
Content-Type:{{contentType}}

{
	"name": "Milo",
	"breedId": 139
}


### Regular use (Scooby Doo) ------------------------------------------------------------------------------------------
POST {{host}}/api/Dog/AddDog
Content-Type:{{contentType}}

{
	"name": "Scooby Doo",
	"breedId": 124
}

### Regular use (Lessie movies) ---------------------------------------------------------------------------------------
POST {{host}}/api/Dog/AddDog
Content-Type:{{contentType}}

{
	"name": "Lessie",
	"breedId": 221
}


### Regular use (BTTF movie) ------------------------------------------------------------------------------------------
POST {{host}}/api/Dog/AddDog
Content-Type:{{contentType}}

{
	"name": "Einstein",
	"breedId": 178
}

### ERROR: Inexistent breed id ----------------------------------------------------------------------------------------
POST {{host}}/api/Dog/AddDog
Content-Type:{{contentType}}

{
	"name": "Pluto",
	"breedId": 2000
}

### ERROR: Duplicated dog ---------------------------------------------------------------------------------------------
POST {{host}}/api/Dog/AddDog
Content-Type:{{contentType}}

{
	"name": "Pluto",
	"breedId": 132
}

### Error parameter: Very large name -----------------------------------------------------------------------------------
POST {{host}}/api/Dog/AddDog
Content-Type: {{contentType}}

{
	"name": "An absurdly long name just to provoke a string size validation error",
	"breedId": 132
}

### Error parameter: Very short name -----------------------------------------------------------------------------------
POST {{host}}/api/Dog/AddDog
Content-Type: {{contentType}}

{
	"name": "Al",
	"breedId": 132
}

### ERROR: Missing parameter ------------------------------------------------------------------------------------------
POST {{host}}/api/Dog/AddDog
Content-Type: {{contentType}}

{
	"name": "Pluto"
}

### ERROR: Missing parameter ------------------------------------------------------------------------------------------
POST {{host}}/api/Dog/AddDog
Content-Type: {{contentType}}

{
	"breedId": 132
}
