@hostname = localhost
@port = 7111
@host = https://{{hostname}}:{{port}}
@contentType = application/json


### FindAvailableDogsBySize ############################################################################################

### Small size --------------------------------------------------------------------------------------------------------
GET {{host}}/api/Dog/FindAvailableDogsBySize?size=s
Content-Type:{{contentType}}

### Medium size -------------------------------------------------------------------------------------------------------
GET {{host}}/api/Dog/FindAvailableDogsBySize?size=M
Content-Type:{{contentType}}

### Large size --------------------------------------------------------------------------------------------------------
GET {{host}}/api/Dog/FindAvailableDogsBySize?size=l
Content-Type:{{contentType}}

### Error parameter (size 'e') ----------------------------------------------------------------------------------------
GET {{host}}/api/Dog/FindAvailableDogsBySize?size=e

### Error missing parameter -------------------------------------------------------------------------------------------
GET {{host}}/api/Dog/FindAvailableDogsBySize